# Generated by Django 4.1.2 on 2022-11-27 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('Matricula', models.IntegerField()),
                ('NombreAlum', models.CharField(max_length=25)),
                ('PaternoAlum', models.CharField(max_length=25)),
                ('MaternoAlum', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoExterior',
            fields=[
                ('idAlumnoExterior', models.AutoField(primary_key=True, serialize=False)),
                ('Matricula', models.IntegerField()),
                ('NombreAlum', models.CharField(max_length=25)),
                ('PaternoAlum', models.CharField(max_length=25)),
                ('MaternoAlum', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('ClaveCarrera', models.IntegerField()),
                ('NombreCarrera', models.CharField(max_length=50)),
                ('Estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAcreditacion',
            fields=[
                ('idDetalleAcreditacion', models.AutoField(primary_key=True, serialize=False)),
                ('CalificacionDE', models.FloatField()),
                ('TipodeExamenDE', models.CharField(max_length=10)),
                ('PeriodoDE', models.CharField(max_length=10)),
                ('CalificacionA', models.FloatField()),
                ('TipodeExamenA', models.CharField(max_length=10)),
                ('PeriodoA', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEquivalencia',
            fields=[
                ('idDetalleEquivalenciaE', models.AutoField(primary_key=True, serialize=False)),
                ('ClaveMatDe', models.IntegerField()),
                ('NombreMatDE', models.CharField(max_length=25)),
                ('CalificacionMatDE', models.FloatField()),
                ('TipoDeExamenDE', models.CharField(max_length=10)),
                ('CreditosMatDE', models.IntegerField()),
                ('PeriodoDE', models.CharField(max_length=10)),
                ('CalificacionA', models.FloatField()),
                ('TipoDeExamenA', models.CharField(max_length=10)),
                ('PeriodoA', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DictamenA',
            fields=[
                ('idDictamenA', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='DictamenE',
            fields=[
                ('idDictamenE', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('PlanEstudioDe', models.CharField(max_length=20)),
                ('CarreraDE', models.CharField(max_length=20)),
                ('idAlumnoExterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.alumnoexterior')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('idEtapa', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEtapa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('ClaveMateria', models.IntegerField()),
                ('NombreMateria', models.CharField(max_length=20)),
                ('Creditos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('idPlanEstudio', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePlanEstudio', models.CharField(max_length=10)),
                ('Estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudioCarrera',
            fields=[
                ('idPlanEstudioCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.carrera')),
                ('idPlanEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudio')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudioCarreraMateria',
            fields=[
                ('idPlanEstudioCarreraMateria', models.AutoField(primary_key=True, serialize=False)),
                ('Estatus', models.BooleanField()),
                ('idEtapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.etapa')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.materia')),
                ('idPlanEstudioCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarrera')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMateria',
            fields=[
                ('idTipoMateria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMateria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniversidadExterior',
            fields=[
                ('idUniversidadExterior', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUniversidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idDocente', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('NombreDocente', models.CharField(max_length=40)),
                ('ApellidoPat', models.CharField(max_length=40)),
                ('ApellidoMat', models.CharField(max_length=40)),
                ('Cargo', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroEquivalenciaComparativa',
            fields=[
                ('idRegistroEquivalenciaComparativa', models.AutoField(primary_key=True, serialize=False)),
                ('idPlanEstudioCarreraMateriaDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarreramateria')),
            ],
        ),
        migrations.AddField(
            model_name='planestudiocarreramateria',
            name='idTipoMateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.tipomateria'),
        ),
        migrations.CreateModel(
            name='DictamenEDetalleEquivalencia',
            fields=[
                ('idDictamenEDetalleEquivalencia', models.AutoField(primary_key=True, serialize=False)),
                ('idDetalleEquivalencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.detalleequivalencia')),
                ('idDictamenE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.dictamene')),
            ],
        ),
        migrations.AddField(
            model_name='dictamene',
            name='idInfoDocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dictamene',
            name='idPlanEstudioCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarrera'),
        ),
        migrations.CreateModel(
            name='DictamenADetalleAcreditacion',
            fields=[
                ('idDictamenADetalleAcreditacion', models.AutoField(primary_key=True, serialize=False)),
                ('idDetalleAcreditacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.detalleacreditacion')),
                ('idDictamenA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.dictamena')),
            ],
        ),
        migrations.AddField(
            model_name='dictamena',
            name='idInfoDocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dictamena',
            name='idPlanEstudioCarreraDE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarrera'),
        ),
        migrations.AddField(
            model_name='detalleequivalencia',
            name='idPlanEstudioCarreraMateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarreramateria'),
        ),
        migrations.AddField(
            model_name='detalleacreditacion',
            name='idPlanEstudioCarreraMateriaDE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.planestudiocarreramateria'),
        ),
        migrations.AddField(
            model_name='alumnoexterior',
            name='idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.carrera'),
        ),
        migrations.AddField(
            model_name='alumnoexterior',
            name='idUniversidadExterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.universidadexterior'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValidacionMaterias.carrera'),
        ),
    ]
